services:
  elasticsearch_logdata:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    build: .
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ingest.geoip.downloader.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic_network
    volumes:
      - esdata1:/usr/share/elasticsearch/data

volumes:
  esdata1:
    driver: local

networks:
  elastic_network: