version: "3"
services:
  elasticsearch_logdata:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    build: .
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic_network
    volumes:
      - esdata1:/usr/share/elasticsearch/data

volumes:
  esdata1:
    driver: local

networks:
  elastic_network: